name: "Render and publish"
on:
  push:
  pull_request:

jobs:
  render-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Install Quarto and render"
        uses: pommevilla/quarto-actions/render-quarto@add-quarto-render
        
      - name: "Deploy to gh-pages branch"
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
